#!/bin/sh

neofetch

#######################
# CUSTOM ENV 
#######################
export MY_CACHE_BCP="$HOME/.cache/bcpscript.txt"
export MY_CACHE_CP="$HOME/.cache/cpscript.txt"
export MY_CACHE_MV="$HOME/.cache/mvscript.txt"
export MY_CACHE_LN="$HOME/.cache/lnscript.txt"

export VISUAL="/usr/bin/nvim"
export EDITOR="$VISUAL"
export CUDA_HOME="/usr/local/cuda-11.3"
export PATH=$PATH:$CUDA_HOME/bin
# export PAGER="most"

#######################
# My settings
#######################
export CDPATH=""
alias cdcg='cd $HOME/cg'
alias cdcomar='cd ~/repos/comars-core/'
alias cdwrite='cd ~/repos/comar-write/'
alias cdpycomar='cd ~/repos/pycomar/'
alias cdvim="cd ~/.config/nvim"
alias cdvimp="cd ~/.local/share/nvim/site/pack/packer/start"
alias cdimgnet="cd ~/dataset-local/imagenet/ILSVRC/Data/CLS-LOC"
alias cdtmp='cd ~/tmp'
alias cdmnt='cd ~/mnt'
alias cdwip='cd ~/wip'
alias cddown='cd ~/Downloads'
alias cdrepo='cd ~/repos'
alias cdbin='cd ~/bin'
alias cdlog='cd ~/mnt/log'
alias cddata='cd ~/mnt/data'
alias iccv='cd ~/wip/iccv2023'
alias lg='lazygit'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/anaconda3/bin/conda" 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

PS1="$(echo "$PS1" | sed 's/(base) //')"

# ENROLL LUA-LSP INTO PATH ENVIRONMENT VARIABLE
alias luamake=$HOME/.config/lsp/lua-language-server/3rd/luamake/luamake
export PATH="${HOME}/.config/lsp/lua-language-server/bin:${PATH}"
export PATH="$HOME/bin:$PATH"

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

alias xsel='xsel -ib'
alias gcal='gcalcli'
alias nvimn='nvim /dev/null'

# SET PWD FOR TMUX
function set_tmux_pwd() {
    [ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD"
    return 0
}
function my_cd() {
    \cd $1
    set_tmux_pwd
}
set_tmux_pwd
alias cd=my_cd
