#!/bin/bash 

name='comars-core'

pushd ~/repos/$name > /dev/null

git pull

git add .
git mcommit "update: auto"

if ! [[ -z $(git status | grep "ahead of 'origin/master") ]]; then
    git push
fi

bash ./build.sh

popd > /dev/null
