#!/bin/bash 

pushd ~/repos/custom-script > /dev/null

git pull

git add .
git mcommit "update: auto"

if ! [[ -z $(git status | grep 'Changes to be committed') ]]; then
    git push
fi

bash ./build.sh

popd > /dev/null
