#!/bin/bash
# cp script generation
path="$HOME/.cache/cpscript.txt"

if [ -z "$path" ]; then
  echo 'Missing -h or -u' >&2
  exit 1
fi

echo "echo From cps program" > $path
for i in $@; do
  echo "cp $(pwd)/$i ./ -rv" >> $path
done
echo "echo cps end" >> $path
