#!/bin/bash

files="llncs.cls macro.tex splncs04.bst"

for f in $files; do
  if [ -f "${f}" ]; then
    rm ${f} -v
  fi
  wget https://raw.githubusercontent.com/KIMGEONUNG/comars-core/master/resource/latex/${f}
done
