#!/bin/bash

wget https://raw.githubusercontent.com/KIMGEONUNG/comars-core/master/resource/latex/llncs.cls
wget https://raw.githubusercontent.com/KIMGEONUNG/comars-core/master/resource/latex/splncs04.bst
wget https://raw.githubusercontent.com/KIMGEONUNG/comars-core/master/resource/latex/macro.tex
