#!/usr/bin/env python

import torchvision.transforms as transforms
from PIL import Image
import os

def parse():
    import argparse
    parser = argparse.ArgumentParser(description='Image center crop')
    parser.add_argument('directory', type=str, default='./')
    parser.add_argument('-p', '--pattern', type=int, required=True,
                        help='target image size')
    return parser.parse_args()


def main():
    args = parse()

    target_dir = args.directory
    target_files = [ os.path.join(target_dir, f) for f in os.listdir(target_dir) ]

    print(target_files)


if __name__ == '__main__':
    main()
