#!/usr/bin/env python

import argparse
import torchvision.transforms as transforms
from PIL import Image

parser = argparse.ArgumentParser()
parser.add_argument('-i', '--input', type=str, required=True, help='input path')
parser.add_argument('-o', '--output', type=str, required=True, help='output path')
parser.add_argument('-s', '--size', type=int, required=True, help='target image size')
args = parser.parse_args()

path_input = args.input
path_output = args.output
size = args.size 
method = Image.BILINEAR

im = Image.open(path_input)
im = transforms.Resize(size, method)(im)
im.save(path_output)
