#!/usr/bin/env python

import torchvision.transforms as transforms
from PIL import Image


def parse():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--input', type=str, required=True,
                        help='input path')
    parser.add_argument('-o', '--output', type=str, required=True,
                        help='output path')
    parser.add_argument('-s', '--size', type=int, required=True,
                        help='target image size')
    return parser.parse_args()


def main():
    args = parse()

    path_input = args.input
    path_output = args.output
    size = args.size
    method = Image.BILINEAR

    im = Image.open(path_input)
    im = transforms.Resize(size, method)(im)
    im.save(path_output)


if __name__ == '__main__':
    main()
