#!/usr/bin/env python

import torchvision.transforms as transforms
from PIL import Image


def parse():
    import argparse
    parser = argparse.ArgumentParser(description='Image rotation')
    parser.add_argument('-i', '--input', type=str, required=True,
                        help='input path')
    parser.add_argument('-o', '--output', type=str, required=True,
                        help='output path')
    parser.add_argument('-d', '--degree', type=int, required=True,
                        help='target image degree')
    return parser.parse_args()


def main():
    args = parse()

    path_input = args.input
    path_output = args.output
    degree = args.degree

    im = Image.open(path_input)
    im = transforms.functional.rotate(im, degree)
    im.save(path_output)
    print('saved image to %s' % (path_output))


if __name__ == '__main__':
    main()
