#!/bin/bash

set -e

dirname=${1}
if [[ -d $dirname ]]; then
  echo -e "\033[31mError: Directory already exists \033[0m" >&2
  exit 1
fi
mkdir -pv $dirname  
shift

for i in $@; do
  ln -sv $(pwd)/$i $dirname
  echo $i
done

exit 0
