#!/bin/bash

set -e

while [[ $# -gt 0 ]]
do
  key="${1}"

  case ${key} in
  -m|--mode)
    mode="${2}"
    shift 2
    ;;
  -h|--help)
    echo "mkdir with files"
    exit 0
    ;;
  *)    # unknown option
    shift # past argument
    ;;
  esac
done


if [ -z "$path" ]; then
  echo 'Missing -h or -u' >&2
  exit 1
fi

dir_name=${1}
shift

echo ${dir_name}
echo ${@}
