#!/bin/bash

set -e

cd ~/repos/comar-write/daily

a=$(date -I)
file=${a}.md

# If not exist, copy the last one for today.
if ! [[ -a ${file} ]]; then
  target=$(ls *.md | sort | tail -n 1)
  cp ${target} ${file} -v
fi

nvim ${file}
