#!/bin/bash
   
path=${1:-./}
for target in $(find $path -maxdepth 1 -type d | xargs realpath); do
    for mnt in $(df -T 2>/dev/null | grep sshfs | awk '{print $7}');do
        if [ $target == $mnt ]; then
            umount $mnt -v
            rmdir $mnt -v
        fi
    done
done
