#!/usr/bin/env python

import sys
import torchvision.transforms as transforms
from PIL import Image
import open3d as o3d



def parse():
    import argparse
    parser = argparse.ArgumentParser(description='Convert ply to xyz')
    return parser.parse_args()


def main():
    args = parse()

    target_files = sys.stdin.read().splitlines()
    print("image gray target files: %d EA" % len(target_files), file=sys.stderr)

    for target_file in target_files:
        pply=o3d.io.read_point_cloud(target_file)

        parts = target_file.split('.')
        head = ''.join(parts[:-1])
        ext = 'xyz'
        path_output = head + ext

        o3d.io.write_point_cloud(path_output, pply)
        print(path_output)

if __name__ == '__main__':
    main()
