#!/usr/bin/env python

import argparse
from pathlib import Path

import open3d as o3d


def parse():
    p = argparse.ArgumentParser()
    p.add_argument("path", type=str)
    return p.parse_args()


def load_mesh(mesh_path):
    mesh = o3d.io.read_triangle_mesh(mesh_path, enable_post_processing=True)
    if mesh.is_empty():
        raise ValueError(f"Failed to load mesh from {mesh_path}")

    if not mesh.has_vertex_normals():
        mesh.compute_vertex_normals()

    return mesh


def visualize_mesh(mesh):
    coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
        size=10.0, origin=[0, 0, 0]
    )
    o3d.visualization.draw_geometries([mesh, coordinate_frame])


if __name__ == "__main__":
    args = parse()
    path = Path(args.path)
    if path.suffix.lower() != ".obj":
        raise ValueError("Invalid extension: expected .obj")

    visualize_mesh(load_mesh(str(path)))
