#!/usr/bin/env python

from PIL import Image
import numpy as np

import argparse


def parse():
    p = argparse.ArgumentParser()
    p.add_argument('path')
    return p.parse_args()


def main():
    args = parse()
    path = args.path
    im = Image.open(path)
    i = 0
    try:
        while 1:
            im.seek(im.tell() + 1)
            i = i + 1
            path_out = path.replace(".gif", "%04d.jpg" % i)
            im.save(path_out, quality=100, subsampling=0)
    except EOFError:
        pass  #


if __name__ == "__main__":
    main()
