#!/usr/bin/env python

import sys
from PIL import Image


def parse():
    import argparse
    parser = argparse.ArgumentParser(description='GIF generation')
    parser.add_argument('-o', '--output', type=str,
            default='./animation.gif', help='output path')
    parser.add_argument('-d', '--duration', type=int,
            default=200, help='for each frame time')
    return parser.parse_args()


def main():
    args = parse()

    target_files = sys.stdin.read().splitlines()
    print("# Target files", file=sys.stderr)
    for i in target_files:
        print(i, file=sys.stderr)

    images = [Image.open(f) for f in target_files]
    images[0].save(args.output, save_all=True,
            append_images=images[1:], optimize=False,
            duration=args.duration, loop=0)

    print(args.output)

if __name__ == '__main__':
    main()
