#!/usr/bin/env python

import sys
from PIL import Image
import webp


def parse():
  import argparse
  parser = argparse.ArgumentParser(description='Image to jpg')
  return parser.parse_args()


def main():
  args = parse()

  target_files = sys.stdin.read().splitlines()
  print("image resize target files: %d EA" % len(target_files),
        file=sys.stderr)

  for target_file in target_files:
    if ".webp" in target_file:
        im = webp.load_image(target_file)
    else:
        im = Image.open(target_file)
    im = im.convert('RGB')

    parts = target_file.split('.')
    head = ''.join(parts[:-1])
    ext = 'png'
    path_output = head + '.' + ext

    im.save(path_output, quality=100, subsampling=0)
    print(path_output)


if __name__ == '__main__':
  main()
