#!/usr/bin/env python3

import sys
import argparse
from PIL import Image
import numpy as np
from cv2 import cv2


def parse():
    p = argparse.ArgumentParser()
    p.add_argument('--fps', type=int, default=30)
    p.add_argument('--path_output', type=str, default='output.mp4')
    return p.parse_args()


def get_img(path):
    img: np.ndarray = np.array(Image.open(path).convert("RGB"))
    img = img[:, :, ::-1]
    return img


def main():
    args = parse()

    target_files = sys.stdin.read().splitlines()
    print("# Target files", file=sys.stderr)
    for i in target_files:
        print(i, file=sys.stderr)

    imgs = [get_img(f) for f in target_files]
    h, w, _ = imgs[0].shape

    out = cv2.VideoWriter(args.path_output,
                          cv2.VideoWriter_fourcc(*'mp4v'),
                          args.fps, (w, h),
                          isColor=True)

    for img in imgs:
        out.write(img)
    out.release()


if __name__ == '__main__':
    main()
