#!/usr/bin/env python

import sys
import torchvision.transforms as transforms
from PIL import Image


def parse():
  import argparse
  parser = argparse.ArgumentParser(description='Convert image to gray')
  parser.add_argument('-r',
                      '--replace',
                      default=False,
                      action='store_true',
                      help='replace input')
  parser.add_argument('--use_rgb',
                      action='store_true',
                      help='save with 3 channel')
  return parser.parse_args()


def main():
  args = parse()

  target_files = sys.stdin.read().splitlines()
  print("image gray target files: %d EA" % len(target_files), file=sys.stderr)
  num_ch = 1
  if args.use_rgb:
    num_ch = 3

  for target_file in target_files:
    im = Image.open(target_file)
    im = transforms.Grayscale(num_ch)(im)

    path_output = None
    if args.replace:
      path_output = target_file
    else:
      parts = target_file.split('.')
      head = ''.join(parts[:-1])
      ext = parts[-1]
      path_output = head + '_gray.' + ext

    im.save(path_output, quality=100, subsampling=0)
    print(path_output)


if __name__ == '__main__':
  main()
