#!/usr/bin/env python3

from cv2 import cv2
import sys


def parse():
    import argparse
    parser = argparse.ArgumentParser(description='Image enhancement')
    parser.add_argument('-r', '--replace', default=False,
                        action='store_true', help='replace input')
    return parser.parse_args()


def main():
    args = parse()

    target_files = sys.stdin.read().splitlines()
    for target_file in target_files:
        img = cv2.imread(target_file, 1)
        # CLAHE (Contrast Limited Adaptive Histogram Equalization)
        clahe = cv2.createCLAHE(clipLimit=3., tileGridSize=(8, 8))

        lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)  # convert from BGR to LAB color space
        l, a, b = cv2.split(lab)  # split on 3 different channels

        l2 = clahe.apply(l)  # apply CLAHE to the L-channel
        lab = cv2.merge((l2, a, b))  # merge channels
        img2 = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)  # convert from LAB to BGR

        if args.replace:
            path_output = target_file
        else:
            parts = target_file.split('.')
            head = ''.join(parts[:-1])
            ext = parts[-1]
            path_output = head + '_enhance' + '.' + ext

        cv2.imwrite(path_output, img2)


if __name__ == '__main__':
    main()
