#!/usr/bin/env python3

from PIL import Image, ImageEnhance
import sys


def parse():
  import argparse
  parser = argparse.ArgumentParser(description='Image color enhance')
  parser.add_argument('--coef', type=float, default=1.5)
  parser.add_argument('-r',
                      '--replace',
                      default=False,
                      action='store_true',
                      help='replace input')
  return parser.parse_args()


def main():
  args = parse()

  target_files = sys.stdin.read().splitlines()
  print("image color enhancement files: %d EA" % len(target_files),
        file=sys.stderr)
  for target_file in target_files:
    im = Image.open(target_file)
    im3 = ImageEnhance.Color(im)
    im = im3.enhance(args.coef)
    if args.replace:
      path_output = target_file
    else:
      parts = target_file.split('.')
      head = ''.join(parts[:-1])
      ext = parts[-1]
      path_output = head + '_color' + '.' + ext

    im.save(path_output)


if __name__ == '__main__':
  main()
