#!/usr/bin/env python

import sys
import torchvision.transforms as transforms
from PIL import Image


def parse():
    import argparse
    parser = argparse.ArgumentParser(description='Image center crop')
    parser.add_argument('-r', '--replace', default=False,
                        action='store_true', help='replace input')
    parser.add_argument('-s', '--size', type=int, default=100,
                        help='target image size')
    return parser.parse_args()


def main():
    args = parse()

    target_files = sys.stdin.read().splitlines()
    print("Target files: %d EA" % len(target_files), file=sys.stderr)

    for target_file in target_files:
        im = Image.open(target_file)
        im = transforms.CenterCrop(args.size)(im)

        path_output = None
        if args.replace:
            path_output = target_file
        else:
            parts = target_file.split('.')
            head = ''.join(parts[:-1])
            ext = parts[-1]
            path_output = head + '_ccrop_%04d.' % (args.size) + ext

        im.save(path_output)
        print(path_output)


if __name__ == '__main__':
    main()
