#!/usr/bin/env python

import sys
import torchvision.transforms as transforms
from PIL import Image


def parse():
    import argparse
    parser = argparse.ArgumentParser(description='Image resize')
    parser.add_argument('-r', '--replace', default=False,
                        action='store_true', help='replace input')
    parser.add_argument('-s', '--size', type=int, required=True,
                        help='target image size')
    return parser.parse_args()


def main():
    args = parse()

    method = transforms.InterpolationMode.BICUBIC
    target_files = sys.stdin.read().splitlines()
    print("# Target files")
    for target_file in target_files:
        print(target_file)

    for target_file in target_files:
        im = Image.open(target_file)
        im = transforms.Resize(args.size, method)(im)

        path_output = None
        if args.replace:
            path_output = target_file
        else:
            parts = target_file.split('.')
            head = ''.join(parts[:-1])
            ext = parts[-1]
            path_output = head + '_resize_%04d.' % (args.size) + ext

        im.save(path_output)
        print('saved image to %s' % (path_output))


if __name__ == '__main__':
    main()
