#!/usr/bin/env python

import sys
import torchvision.transforms as transforms
from torchvision.transforms import ToTensor, ToPILImage

from PIL import Image


def parse():
    import argparse
    parser = argparse.ArgumentParser(description='Split image')
    parser.add_argument('path', help='target image path')
    parser.add_argument('--prefix', default='unknown')
    parser.add_argument('-n',
                        '--num',
                        type=int,
                        default=3,
                        help='target image size')
    return parser.parse_args()


def main():
    args = parse()
    im = Image.open(args.path)
    x = ToTensor()(im)
    length = x.shape[-1]
    sublength = length // args.num

    for i in range(args.num):
        y = x[..., i * sublength:(i + 1) * sublength]
        im = ToPILImage()(y)
        im.save(f'{args.prefix}_{i:02d}.png')

if __name__ == '__main__':
    main()
