#!/usr/bin/env python

import sys
from torchvision.transforms import ToTensor, ToPILImage
from PIL import Image


def parse():
  import argparse
  parser = argparse.ArgumentParser(description='Image resize')
  parser.add_argument('-r',
                      '--replace',
                      default=False,
                      action='store_true',
                      help='replace input')
  parser.add_argument('-s',
                      '--scale',
                      type=int,
                      default=100,
                      help='target scale')
  return parser.parse_args()


def main():
  args = parse()

  if len(args.size) > 2:
    raise Exception('Invalid image size')

  target_files = sys.stdin.read().splitlines()
  print("image resize target files: %d EA" % len(target_files),
        file=sys.stderr)

  for target_file in target_files:
    im = Image.open(target_file)
    x = ToTensor()(im)
    x = x.mul(args.scale).clip(0, 1)
    im = ToPILImage()(x)

    path_output = None
    if args.replace:
      path_output = target_file
    else:
      parts = target_file.split('.')
      head = ''.join(parts[:-1])
      ext = parts[-1]
      info = '_'.join([str(i) for i in args.size])
      path_output = head + '_scale_' + info + '.' + ext

    im.save(path_output)
    print(path_output)


if __name__ == '__main__':
  main()
