#!/bin/bash

__ScriptVersion="1.0.0"

#===  FUNCTION  ================================================================
#         NAME:  usage
#  DESCRIPTION:  Display usage information.
#===============================================================================
function usage ()
{
    echo "Usage :  $0 [options] [--]

    Get sample image from server

    Options:
    -h|help       Display this message
    -v|version    Display script version"

}    # ----------  end of function usage  ----------

#-----------------------------------------------------------------------
#  Handle command line arguments
#-----------------------------------------------------------------------

while getopts ":hv" opt
do
  case $opt in

    h|help     )  usage; exit 0   ;;

    v|version  )  echo "$0 -- Version $__ScriptVersion"; exit 0   ;;

    * )  echo -e "\n  Option does not exist : $OPTARG\n"
          usage; exit 1   ;;

  esac    # --- end of case ---
done
shift $(($OPTIND-1))

num=${1:-1}
num=$(seq -f "%02g" $num $num) 
name_file=sample${num}.jpg

address=https://raw.githubusercontent.com/KIMGEONUNG/comars-core/master/resource/$name_file

rs=$(wget $address -O $name_file 2>&1 | grep -e 'Not Found')

if [[ -n $rs ]]; then
    echo Error: no such a file at server
    rm $name_file
    exit 1
else
    echo $name_file
    exit 0
fi
