#!/usr/bin/env python

import sys
import torchvision.transforms as transforms
from torchvision.utils import make_grid
from PIL import Image


def parse():
    import argparse
    parser = argparse.ArgumentParser(description='Image view with grid')
    parser.add_argument('--num', type=int, default=16)
    return parser.parse_args()


def main():
    args = parse()

    target_files = sys.stdin.read().splitlines()
    num_total = len(target_files)
    print("total files: ", num_total)

    num_col = int(num_total ** 0.5)









    




if __name__ == '__main__':
    main()
