#!/usr/bin/env python3

from scipy.io import loadmat
import argparse
import matplotlib.pyplot as plt
import numpy as np 


def parse():
    p = argparse.ArgumentParser()
    p.add_argument('path', type=str) 
    p.add_argument('--scale', type=float, default=1.0) 
    p.add_argument('--gray', action='store_true') 

    return p.parse_args()


def main():
    args = parse()
    path_input = args.path

    img: np.ndarray = loadmat(path_input)['noisy_list']
    img = img.astype('float32') / (2 ** 16)

    if args.gray:
        img = img[..., 3]
    else:
        img = img[..., :3]

    img = img * args.scale
    img = img.clip(0, 1)

    plt.rcParams["figure.figsize"] = (20,20)
    if args.gray:
        plt.imshow(img, cmap='gray')
    else:
        plt.imshow(img)
    plt.tight_layout()
    plt.show()


if __name__ == '__main__':
    main()
