#!/usr/bin/env python3

import sys
from scipy.io import loadmat
import argparse
import numpy as np
import cv2
import re


def parse():
  p = argparse.ArgumentParser()
  p.add_argument('--scale', type=float, default=1.0)
  return p.parse_args()


def get_img(path):
  img: np.ndarray = loadmat(path)['noisy_list']
  img = img.astype('float32') / (2**16) * 255
  img = img[..., :3][..., ::-1]

  return img


def scale_img(img, scale):
  img = img * scale
  img = img.clip(0, 1)
  return img


def main():
  args = parse()
  target_files = sys.stdin.read().splitlines()
  print("# Target files", file=sys.stderr)
  for f in target_files:
    path_out = re.sub('mat$', 'jpg', f)

    img: np.ndarray = loadmat(f)['noisy_list']
    img = img.astype('float32') / (2**16)
    img = img * args.scale
    img = img.clip(0, 1)
    img = img * 255
    img = img[..., :3][..., ::-1]

    cv2.imwrite(path_out, img)
    print(path_out, file=sys.stderr)


if __name__ == '__main__':
  main()
