#!/usr/bin/env python3

import os
import cv2
from moviepy.editor import VideoFileClip
from PIL import Image
from pathlib import Path


def parse():
    import argparse
    parser = argparse.ArgumentParser(description='mp4 to gif conversion')
    parser.add_argument('path', help='input')
    parser.add_argument('-i',
                        '--interval',
                        type=int,
                        default=1,
                        help='frame interval')
    parser.add_argument('--limit',
                        type=int,
                        default=1000,
                        help='frame interval')
    parser.add_argument('--size',
                        type=int,
                        default=None,
                        help='frame interval')

    return parser.parse_args()


if __name__ == "__main__":
    args = parse()
    path_input = args.path
    name = Path(path_input).stem

    vidcap = cv2.VideoCapture(path_input)
    frames = []
    count = 0
    interval = args.interval

    success, image = vidcap.read()
    while success:
        if args.limit < len(frames):
            break

        # Save frame as JPEG file if it's the nth frame
        if count % interval == 0:
            frames.append(Image.fromarray(image[:, :, ::-1]))

        success, image = vidcap.read()
        count += 1

    print(f'Total Count : {count}')
    print(f'Frame Count : {len(frames)}')

    os.makedirs(f'{name}')

    for i, frame in enumerate(frames):
        frame.save(f"{name}/{i:03d}.png")
