#!/usr/bin/env python

from skimage.metrics import peak_signal_noise_ratio as compare_psnr

from PIL import Image
from torchvision.transforms import ToTensor

import argparse


def parse():
    parser = argparse.ArgumentParser(description='Calculate PSNR')
    parser.add_argument('path', nargs=2)
    parser.add_argument('--verbose', action='store_true')
    return parser.parse_args()


args = parse()
path1, path2 = args.path

if args.verbose:
    print('1st path: %s' % (path1))
    print('2nd path: %s' % (path2))

im1 = Image.open(path1)
im2 = Image.open(path2)

x1 = ToTensor()(im1).permute(2, 1, 0).numpy()
x2 = ToTensor()(im2).permute(2, 1, 0).numpy()

psnr = compare_psnr(x1, x2)
print(psnr)
