#!/bin/bash

if [[ -z ${1} ]]; then
    echo Error: enter user name as first argument
fi

if [[ "$2" == "mosh" ]]; then
    mosh --ssh="ssh -p 6000" "$1@141.223.92.5"
else
    ssh "$1@141.223.92.5" -p 6000 -Y
fi
