#!/bin/bash

uid=$(id -u)
gid=$(id -g)

dir_data=data
dir_log=log

mkdir -p $dir_data
sudo mount -t cifs //bean.postech.ac.kr/data/kkw ./$dir_data -o user=cgkorea,uid=$uid,gid=$gid

mkdir -p $dir_log
sudo mount -t cifs //bean.postech.ac.kr/log/kkw ./$dir_log -o user=cgkorea,uid=$uid,gid=$gid
